### ISSUE TITLE
GitHub Workflow: Deploy documentation fails if there is no change

### ISSUE THREAD

**Issue by luator** [machines-in-motion/mpi_cmake_modules#41]
The deployment of documentation was failing in the last run:
https://github.com/machines-in-motion/mpi_cmake_modules/runs/3963580279?check_suite_focus=true#step:6:108

The cause for this is that the [git commit](https://github.com/machines-in-motion/mpi_cmake_modules/blob/33cb87d04e1a54d01bbc375b418bc50e123d4cf7/.github/workflows/deploy_doc.yml#L77) fails if there was no actual change in the documentation files (and thus nothing to commit).
So there should be some check if anything actually changed (e.g. like [this](https://stackoverflow.com/a/25149786/2095383)).

**Comment by MaximilienNaveau** [comment]
Was it updated?

**Comment by luator** [comment]
The workflow hasn't changed, so I assume the issue still exists.  I think to test, we would need to trigger it with a change that does not affect documentation in any way.

**Comment by MaximilienNaveau** [comment]
just launch the workflow manually without any any change in the code.
You can do that in the action tab

**Comment by luator** [comment]
Still fails with
```
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
Error: Process completed with exit code 1.
```

**Comment by MaximilienNaveau** [comment]
I believe I fixed it

**Comment by MaximilienNaveau** [comment]
Fill free to re-open in case of trouble.
This change needs to be propagated to all other repos.
We need an independent github action for this but I did not had time to configure one properly
