### ISSUE TITLE
Reactive Planners Build doesn't work

### ISSUE THREAD

**Issue by emrecemal** [machines-in-motion/mpi_cmake_modules#51]
Hello,

I try to install packages on my computer, but I couldn't build dependencies. Here is the result of `colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release`

You can find the events.log and logger_all.log for details.

Ubuntu 18.04
Anaconda Python 3.6

```
Starting >>> googletest-distribution
Starting >>> mpi_cmake_modules
Starting >>> pybind11
--- stderr: mpi_cmake_modules                                                
CMake Error at cmake/sphinx.cmake:65 (message):
  breathing-cat not found! Please install using: pip3 install breathing-cat
Call Stack (most recent call first):
  cmake/documentation.cmake:43 (add_sphinx_documentation)
  CMakeLists.txt:85 (add_documentation)


---
Failed   <<< mpi_cmake_modules [0.66s, exited with code 1]
Aborted  <<< pybind11 [0.81s]                    
Aborted  <<< googletest-distribution [1.01s]                            

Summary: 0 packages finished [1.62s]
  1 package failed: mpi_cmake_modules
  2 packages aborted: googletest-distribution pybind11
  2 packages had stderr output: mpi_cmake_modules pybind11
  7 packages not processed

[events.log](https://github.com/machines-in-motion/reactive_planners/files/9952151/events.log)
[logger_all.log](https://github.com/machines-in-motion/reactive_planners/files/9952152/logger_all.log)
```

When I try to install breathing-cat: `pip3 install breathing-cat`

```
ERROR: Could not find a version that satisfies the requirement breathing-cat (from versions: none)
ERROR: No matching distribution found for breathing-cat
```

**Comment by MaximilienNaveau** [comment]
@luator did we actually exported breathing-cat into pip?

@emrecemal the repository you are looking for is this one:
https://github.com/machines-in-motion/breathing-cat/
Please try to download it into your workspace/src folder and rebuild.

Let me know here if you have any other issues.

**Comment by luator** [comment]
Yes, breathing cat is on PyPI, however, it has a minimum requirement of Python 3.8 :/

We should try to change the cmake files, such that it only checks for the existence of breathing cat when actually building the documentation (with `-DGENERATE_DOCUMENTATION=ON`).

**Comment by MaximilienNaveau** [comment]
PR is merged @emrecemal could you try again?
